version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQLComposeContainerServer
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Test123!"
    ports:
      - "14330:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Test123!", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - sql_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Is.Web/Dockerfile
    container_name: kiii-compose-container
    ports:
      - "8081:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=isDb;User Id=sa;Password=Test123!;Encrypt=False;TrustServerCertificate=True;

volumes:
  sql_data:
