apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-deployment
  namespace: kiii-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiii-app
  template:
    metadata:
      labels:
        app: kiii-app
    spec:
      containers:
        - name: kiii-container
          image: macccy/kiii-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIORNMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
              value: "false"
            - name: Logging__LogLevel__Microsoft
              value: "Information"
          envFrom:
            - configMapRef:
                name: kiii-config
            - secretRef:
                name: kiii-secrets