apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: kiii-ingress
 namespace: kiii-app-namespace
spec:
 ingressClassName: nginx
 rules:
  - host: kiii.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: kiii-service
          port:
           number: 80