apiVersion: v1
kind: Secret
metadata:
  name: kiii-secrets
  namespace: kiii-app-namespace
type: Opaque
stringData:
  SQL_CONNECTION_STRING: "Server=sqlcontinerserver,1433;Database=isDb;User Id=sa;Password=Test123!;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True"
  