apiVersion: v1
kind: Service
metadata:
 name: kiii-service
 namespace: kiii-app-namespace
spec:
 selector:
  app: kiii-app
 type: NodePort
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
